import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

const data = [
    {
        id: '1',
        name: 'Brendan',
        phone: '1-724-406-2487',
        company:
            'ZEnim Commodo Limited Enim Commodo Limited Enim Commodo LimitedEnim Commodo Limited',
        zip: '98611',
        city: 'Norman',
        date: '02/13/14',
        country: 'Bangladesh',
        img: 'https://media.giphy.com/media/65NgeYxfJ3aqCbgHL7/giphy.gif',
    },
    {
        id: '26',
        name: 'John',
        phone: '1-724-406-1234',
        company: 'Enim Commodo Limited',
        zip: '98622',
        city: 'Chicago',
        date: '06/03/01',
        country: 'USA',
        img: 'https://media.giphy.com/media/3nbxypT20Ulmo/giphy.gif',
        manager: '1',
    },
    {
        id: '27',
        name: 'Emma',
        phone: '1-724-406-1234',
        company: 'Enim Commodo Limited',
        zip: '98622',
        city: 'Colorado',
        date: '04/12/04',
        country: 'USA',
        img: 'https://media.giphy.com/media/3nbxypT20Ulmo/giphy.gif',
        manager: '1',
    },
    {
        id: '2',
        name: 'Warren',
        phone: '1-412-485-9725',
        company: 'ZOdio Etiam Institute',
        zip: '10312',
        city: 'Sautin',
        date: '01/01/13',
        country: 'India',
        img: 'https://media.giphy.com/media/rrmf3fICPZWg1MMXOW/giphy.gif',
    },
    {
        id: '3',
        name: 'Brendan',
        phone: '1-724-406-2487',
        company: 'YEnim Commodo Limited',
        zip: '98611',
        city: 'Norman',
        date: '02/13/14',
        country: 'Bangladesh',
        img: 'https://media.giphy.com/media/65NgeYxfJ3aqCbgHL7/giphy.gif',
    },
    {
        id: '4',
        name: 'Rarren',
        phone: '1-412-485-9725',
        company: 'Odio Etiam Institute',
        zip: '10312',
        city: 'Sautin',
        date: '01/01/13',
        country: 'India',
        img: 'https://media.giphy.com/media/65NgeYxfJ3aqCbgHL7/giphy.gif',
    },
    {
        id: '5',
        name: 'dssendan',
        phone: '1-724-406-2487',
        company: 'Enim Commodo Limited',
        zip: '98611',
        city: 'Norman',
        date: '02/13/14',
        country: 'Bangladesh',
        img: 'https://media.giphy.com/media/65NgeYxfJ3aqCbgHL7/giphy.gif',
    },
    {
        id: '6',
        name: 'Warren',
        phone: '1-412-485-9725',
        company: 'Odio Etiam Institute',
        zip: '10312',
        city: 'Sautin',
        date: '01/01/13',
        country: 'India',
        img: 'https://media.giphy.com/media/65NgeYxfJ3aqCbgHL7/giphy.gif',
    },
    {
        id: '7',
        name: 'Brendan',
        phone: '1-724-406-2487',
        company: 'Enim Commodo Limited',
        zip: '98611',
        city: 'Norman',
        date: '02/13/14',
        country: 'Bangladesh',
        img: 'https://media.giphy.com/media/65NgeYxfJ3aqCbgHL7/giphy.gif',
    },
    {
        id: '8',
        name: 'Warren',
        phone: '1-412-485-9725',
        company: 'Odio Etiam Institute',
        zip: '10312',
        city: 'Sautin',
        date: '01/01/13',
        country: 'India',
        img: 'https://media.giphy.com/media/rrmf3fICPZWg1MMXOW/giphy.gif',
    },
    {
        id: '9',
        name: 'Brendan',
        phone: '1-724-406-2487',
        company: 'Enim Commodo Limited',
        zip: '98611',
        city: 'Norman',
        date: '02/13/14',
        country: 'Bangladesh',
        img: 'https://media.giphy.com/media/65NgeYxfJ3aqCbgHL7/giphy.gif',
    },
    {
        id: '10',
        name: 'Warren',
        phone: '1-412-485-9725',
        company: 'Odio Etiam Institute',
        zip: '10312',
        city: 'Sautin',
        date: '01/01/13',
        country: 'India',
        img: 'https://media.giphy.com/media/rrmf3fICPZWg1MMXOW/giphy.gif',
    },
    {
        id: '11',
        name: 'Brendan',
        phone: '1-724-406-2487',
        company: 'Enim Commodo Limited',
        zip: '98611',
        city: 'Norman',
        date: '02/13/14',
        country: 'Bangladesh',
        img: 'https://media.giphy.com/media/65NgeYxfJ3aqCbgHL7/giphy.gif',
    },
    {
        id: '12',
        name: 'Warren',
        phone: '1-412-485-9725',
        company: 'Odio Etiam Institute',
        zip: '10312',
        city: 'Sautin',
        date: '01/01/13',
        country: 'India',
        img: 'https://media.giphy.com/media/65NgeYxfJ3aqCbgHL7/giphy.gif',
    },
    {
        id: '13',
        name: 'Brendan',
        phone: '1-724-406-2487',
        company: 'Enim Commodo Limited',
        zip: '98611',
        city: 'Norman',
        date: '02/13/14',
        country: 'Bangladesh',
        img: 'https://media.giphy.com/media/65NgeYxfJ3aqCbgHL7/giphy.gif',
    },
    {
        id: '14',
        name: 'Warren',
        phone: '1-412-485-9725',
        company: 'Odio Etiam Institute',
        zip: '10312',
        city: 'Sautin',
        date: '01/01/13',
        country: 'India',
        img: 'https://media.giphy.com/media/rrmf3fICPZWg1MMXOW/giphy.gif',
    },
    {
        id: '15',
        name: 'Brendan',
        phone: '1-724-406-2487',
        company: 'Enim Commodo Limited',
        zip: '98611',
        city: 'Norman',
        date: '02/13/14',
        country: 'Bangladesh',
        img: 'https://media.giphy.com/media/duNowzaVje6Di3hnOu/giphy.gif',
    },
    {
        id: '16',
        name: 'Warren',
        phone: '1-412-485-9725',
        company: 'Odio Etiam Institute',
        zip: '10312',
        city: 'Sautin',
        date: '01/01/13',
        country: 'India',
        img: 'https://media.giphy.com/media/duNowzaVje6Di3hnOu/giphy.gif',
    },
    {
        id: '17',
        name: 'Brendan',
        phone: '1-724-406-2487',
        company: 'Enim Commodo Limited',
        zip: '98611',
        city: 'Norman',
        date: '02/13/14',
        country: 'Bangladesh',
        img: 'https://media.giphy.com/media/65NgeYxfJ3aqCbgHL7/giphy.gif',
    },
    {
        id: '18',
        name: 'Warren',
        phone: '1-412-485-9725',
        company: 'Odio Etiam Institute',
        zip: '10312',
        city: 'Sautin',
        date: '01/01/13',
        country: 'India',
        img: 'https://media.giphy.com/media/65NgeYxfJ3aqCbgHL7/giphy.gif',
    },
    {
        id: '19',
        name: 'Brendan',
        phone: '1-724-406-2487',
        company: 'Enim Commodo Limited',
        zip: '98611',
        city: 'Norman',
        date: '02/13/14',
        country: 'Bangladesh',
        img: 'https://media.giphy.com/media/duNowzaVje6Di3hnOu/giphy.gif',
    },
    {
        id: '20',
        name: 'Warren',
        phone: '1-412-485-9725',
        company: 'Odio Etiam Institute',
        zip: '10312',
        city: 'Sautin',
        date: '01/01/13',
        country: 'India',
        img: 'https://media.giphy.com/media/65NgeYxfJ3aqCbgHL7/giphy.gif',
    },
    {
        id: '21',
        name: 'Brendan',
        phone: '1-724-406-2487',
        company: 'Enim Commodo Limited',
        zip: '98611',
        city: 'Norman',
        date: '02/13/14',
        country: 'Bangladesh',
        img: 'https://media.giphy.com/media/duNowzaVje6Di3hnOu/giphy.gif',
    },
    {
        id: '22',
        name: 'Warren',
        phone: '1-412-485-9725',
        company: 'Odio Etiam Institute',
        zip: '10312',
        city: 'Sautin',
        date: '01/01/13',
        country: 'India',
        img: 'https://media.giphy.com/media/65NgeYxfJ3aqCbgHL7/giphy.gif',
    },
    {
        id: '23',
        name: 'Brendan',
        phone: '1-724-406-2487',
        company: 'Enim Commodo Limited',
        zip: '98611',
        city: 'Norman',
        date: '02/13/14',
        country: 'Bangladesh',
        img: 'https://media.giphy.com/media/65NgeYxfJ3aqCbgHL7/giphy.gif',
    },
    {
        id: '24',
        name: 'Warren',
        phone: '1-412-485-9725',
        company: 'Odio Etiam Institute',
        zip: '10312',
        city: 'Sautin',
        date: '01/01/13',
        country: 'India',
        img: 'https://media.giphy.com/media/duNowzaVje6Di3hnOu/giphy.gif',
    },
    {
        id: '25',
        name: 'Brendan',
        phone: '1-724-406-2487',
        company:
            'ZEnim Commodo Limited Enim Commodo Limited Enim Commodo LimitedEnim Commodo Limited',
        zip: '98611',
        city: 'Norman',
        date: '02/13/14',
        country: 'Bangladesh',
        img: 'https://media.giphy.com/media/65NgeYxfJ3aqCbgHL7/giphy.gif',
    },
];

@Injectable({
    providedIn: 'root',
})
export class GridDataService {
    private rowsData = new BehaviorSubject(data);
    public rowsData$ = this.rowsData.asObservable();
}
